services:
  odoo:
    image: odoo:17.0
    restart: always
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./volumes/config:/etc/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./volumes/addons:/mnt/extra-addons
    env_file:
      - .env
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
  nginx:
    image: nginx
    restart: always
    ports:
      - "${NGINX_EXPOSED_PORT}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./start-nginx.sh:/tmp/start-nginx.sh
      - ${NGINX_SSL_CERTIFICATE_PATH}:/etc/ssl/certs/ssl.pem
      - ${NGINX_SSL_CERTIFICATE_KEY_PATH}:/etc/ssl/certs/ssl.key
    env_file:
      - .env
    depends_on:
      - odoo
volumes:
  odoo-web-data:
  odoo-db-data: